name: interklima_produkcja
description: Aplikacja ewidencji czasu pracy - DziaÅ‚ Produkcja

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/interklima_icon.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/images/interklima_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_transparent.png
    - assets/images/interklima_icon.png
